version: "3.8"
services:
  books-database:
    image: humbertobonadiman/books-database
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books-database
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.database": "books",
        "spring.data.mongodb.port": "27017",
        "spring.data.mongodb.host": "mongodb"
      }'
    networks:
      - books-database-net
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - books-database-net
networks:
  books-database-net:
    driver: bridge
volumes:
  db: